name: Dev
variables:
  - name: api_url_local
    value: http://localhost:8000
  - name: token
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3Mzg1NDk3LCJpYXQiOjE3NzcyOTkwOTcsImp0aSI6IjZlNjBkOGE1ODBhYTQ4ZDhhMDE3NjczYzZiYjc3OGZhIiwidXNlcl9pZCI6ImNhMGUxN2IxLTg2ZjgtNDdhZC05ZDIwLTYxMjIxNzczZTdjMiIsImVtYWlsIjoiZXBhbGF1QGdtYWlsLmNvbSIsIm5vbWJyZSI6IkVkdWFyZG8gUGFsYXUiLCJyb2wiOiJBU0lTVEVOVEUifQ.tW69QLF9TsKkGXZS1ZrU8nT0p8b4xkrTF5MhsodRtFI
